### ISSUE TITLE
JOSS - Confusion about closest sptype

### ISSUE THREAD

**Issue by wtgee** [bmorris3/arcesetc#10]
In the [Getting Started](https://arcesetc.readthedocs.io/en/latest/arcesetc/gettingstarted.html) guide there is a note on the first example that `G4V` -> `G5V` because there is no exact match but in the [example notebook](https://github.com/bmorris3/arcesetc/blob/master/notebooks/example.ipynb) it points out that it will try to guess the type if something is close and give a `ValueError` warning.

I can see in [`closest_sptype`](https://github.com/bmorris3/arcesetc/blob/master/arcesetc/util.py#L39) that there is some special handling of `xxV` types. Some clarification of when it is corrected would be helpful.

**Comment by bmorris3** [comment]
Thanks for this. The doctoring has been clarified in the above commit.
